title: Argument Annotation and Evaluation tool
description: Tool for the annotation and evaluation of arguments in a massive and simple way.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
